#!/bin/sh
#
# DESCRIPTION
#
# Startup init script for BackupPC on suse linux.
#
# Distributed with BackupPC version __VERSION__, released __RELEASEDATE__.
#

set -e

#
BINDIR=__INSTALLDIR__/bin
DATADIR=__TOPDIR__
RUNDIR=__RUNDIR__
USER=__BACKUPPCUSER__
#
NAME=backuppc
DAEMON=BackupPC

test -x $BINDIR/$DAEMON || exit 0

if [ ! -d $RUNDIR ]; then
    mkdir -p $RUNDIR
    chown $USER $RUNDIR
    chmod 0755 $RUNDIR
fi

case "$1" in
  start)
    echo -n "Starting $NAME: "
    startproc -f  -p $RUNDIR/BackupPC.pid -u $USER $BINDIR/$DAEMON -d
    echo "ok."
    ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $RUNDIR/BackupPC.pid -u $USER \
			    --oknodo
    echo "ok."
      ;;
  restart)
    echo -n "Stopping $NAME: "
    start-stop-daemon --stop --pidfile $RUNDIR/BackupPC.pid -u $USER \
			    --oknodo
    echo "ok."
    echo -n "Starting $NAME: "
    startproc -f  -p $RUNDIR/BackupPC.pid -u $USER $BINDIR/$DAEMON -d
    echo "ok."
    ;;
  reload|force-reload)
    echo "Reloading $NAME configuration files"
    start-stop-daemon --stop --pidfile $RUNDIR/BackupPC.pid \
			    --signal 1 -x /usr/bin/perl
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0
